### ISSUE TITLE
More straightforward interface

### ISSUE THREAD

**Issue by isabanin** [leonbarrett/BeanstalkCommandLine#9]
Hey guys,

Have you considered making the interface more straightforward? I would love to do something like this:

```
$ beanstalk deploy repository environment -m "Deploy message here" -r REVISION
```

Right now you have to go through so many steps to initiate a deployment that it almost takes the same amount of time as launching a web browser and doing it through the web interface.

Thanks,
Ilya Sabanin

**Comment by leonbarrett** [comment]
Hi, yes I have thought about making this more intuitive by being able to pass all options into a single command. Hopefully over the Xmas break I'll be able to work on this a bit more :-)

**Comment by isabanin** [comment]
Awesome news, thanks Leon!

**Comment by leonbarrett** [comment]
Hi, I'm working on an updated tool now so that the options can be passed as a single call with a confirmation at the end.

At present the options are:
- -m = method, i.e repo:deploy, repo:create
- -r = respostory
- -e = environment
- -v = version
- -c = comment

For example calling `beanstalk -m repo:deploy -r test-repo -e Staging -c "this is a test"` would deploy the latest revision of the test-repo to the Staging environment with a message of this is a test.

I'm thinking that if optional parameters are not passed then defaults are used where appropriate, but either way you aren't prompted (i.e for a comment). This should hopefully make things faster and easier to use.

I've switched to a new method of parsing the input which requires re-writing almost every function so it will take me a while to complete. If you want to test with an alpha version I can email that to you (at the moment only repo:deploy is working)

**Comment by isabanin** [comment]
Thanks Leon!
